### PR TITLE
Add additional MM enums and minor additions to blocking modem interface

### PR DESCRIPTION
**Pull request by BubuOT**

### CODE REVIEW

**Comment by BubuOT** [comment]
I was a bit confused about some things only being available in the blocking and some only in the async api so far. I suppose the idea would be to have a consistent api across both? (It's a bit unfortunate that you essentially have to write everything twice, but I suppose that's the way to do it with sdbus?

Another thing I was wondering about: the `simple.get_status()` call returns raw types, it looks i.e. like this:
```
{'state': ('u', 11), 'signal-quality': ('(ub)', (57, True)), 'current-bands': ('au', [1, 2, 5, 10, 31, 33, 37, 38, 50, 58]), 'access-technologies': ('u', 16386), 'm3gpp-registration-state': ('u', 5), 'm3gpp-operator-code': ('s', '26202'), 'm3gpp-operator-name': ('s', 'vodafone.de')}
```
Would it make sense to have another method that returns a "nicer" representation of this?

I.e. something like:
```
{
'state': MM_MODEM_STATE_CONNECTED,
'signal-quality': (57, True).
 'current-bands': [1, 2, 5, 10, 31, 33, 37, 38, 50, 58],
 'access-technologies': 'MM_MODEM_ACCESS_TECHNOLOGY_GSM|MM_MODEM_ACCESS_TECHNOLOGY_LTE',  # IntFlag type
 'm3gpp-registration-state':  MM_MODEM_3GPP_REGISTRATION_STATE_ROAMING,
 'm3gpp-operator-name': 'vodafone.de'.
}
```

Is this something that would make sense to you? Any idea how this api should be called and in which subpackage it would live?

And yet another question :sweat_smile:: What's your stance on type hints? Should these be added to all the existing blocking code as well? I can maybe do that in a followup PR.

**Comment by igo95862** [comment]
> Another thing I was wondering about: the `simple.get_status()` call returns raw types, it looks i.e. like this:

It is a D-Bus type of `a{sv}` which is a dictionary of keys as strings and values are variants. A variant is a tuple D-Bus type signature and a value.

If you want a quick conversion to unvarianted values you can use the dictionary comprehension:

```python
d = {"a": ("x", 2)}
print(d)  # Prints: {'a': ('x', 2)}
du = {k: dv for k, (dt, dv) in d.items()}
print(du)  # Prints: {'a': 2}
```

However, this does not account for nested variants.

**Comment by zhanglongqi** [comment]
Yes, keep them consistent will be easier for the maintenance. Comparing with the type checking, we can working on the interface consistence  first. I did not implement all of them at the beginning because I was rushing on the timeline, you can add more to keep them consistant. For the type checker I think we can keep it for now so it will consistant with the other sdbus library.

**Comment by zhanglongqi** [comment]
Yes, keep them consistent will be easier for the maintenance. Comparing with the type checking, we can working on the interface consistance  first. I did not implement all of them at the beginning because I was rushing on the timeline, you can add more to keep them consistant. For the type checker I think we can keep it for now so it will consistant with the other sdbus library.

**Pull request merged**
